# Generated by Django 5.2 on 2025-04-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(upload_to="usres/profiles", verbose_name="profile image"),
        ),
    ]
