# Generated by Django 5.2 on 2025-04-19 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='discription')),
                ('is_private', models.BooleanField(default=False, verbose_name='is private')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rooms', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('is_muted', models.BooleanField(default=False, verbose_name='is muted')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_members', to='rooms.room', verbose_name='room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_rooms', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to='rooms.room', verbose_name='room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roommember', verbose_name='sender')),
            ],
        ),
    ]
