# Generated by Django 5.2 on 2025-04-20 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/profiles', verbose_name='room avatar'),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('music_file', models.FileField(upload_to='rooms/musics', verbose_name='File (optional)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='rooms.room', verbose_name='Room')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
        ),
    ]
